replicaCount: 1

image:
  repository: gabbi/sample-cloudsdk-java:0.0.1
  pullPolicy: IfNotPresent

securityContext:
  capabilities:
   drop:
   - ALL
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 80

resources: {}

application:
  tenantName: my-mktng-tenant
  servicePath: "/sap/opu/odata/SAP/API_MKT_CAMPAIGN_SRV;v=0002"