apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sample-cloudsdk-java.fullname" . }}
  labels:
    {{- include "sample-cloudsdk-java.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "sample-cloudsdk-java.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sample-cloudsdk-java.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          - name: APPLICATION_TENANT_NAME
            value: {{ .Values.application.tenantName }}
          - name: APPLICATION_SERVICE_PATH
            value: {{ .Values.application.servicePath }}
          - name: destinations
            value: '[{name: "$(APPLICATION_TENANT_NAME)", url: "$(URL)", username: "$(User)", password: "$(Password)"}]'